sudo: true

install:
  - sudo apt-get update
  - sudo apt-get -y install make pandoc
  - sudo apt-get -y install \
          texlive texlive-base texlive-binaries \
          texlive-fonts-recommended texlive-latex-base texlive-latex-extra \
          texlive-latex-recommended texlive-pictures texlive-plain-generic texlive-xetex


script:
  - make

after_success:
- .travis/push.sh
