sudo: true

install:
  - sudo apt-get update
  - sudo apt-get -y install make pandoc
  - sudo apt-get -y install
          texlive texlive-base texlive-binaries
          texlive-fonts-recommended texlive-latex-base texlive-latex-extra
          texlive-latex-recommended texlive-pictures texlive-xetex
  - sudo apt-get -y install fonts-freefont-otf fonts-freefont-ttf


script:
  - make

after_success:

- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"

- git checkout -b travis-temp
- git add *.pdf
- git commit --message "Travis build"
- git checkout master
- git merge travis-temp

- git remote add origin-temp https://${GH_TOKEN}@github.com/EAL-IT-Technology/ITT3-Special-subjects.git
- git push --set-upstream origin-temp
