sudo: true

install:
  - sudo apt-get update
  - sudo apt-get -y install make pandoc
  - sudo apt-get -y install
          texlive texlive-base texlive-binaries
          texlive-fonts-recommended texlive-latex-base texlive-latex-extra
          texlive-latex-recommended texlive-pictures texlive-xetex


script:
  - make

after_success:

- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"

- git checkout -b master
- git add . *.pdf

- git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"

- git remote add origin-pages https://${GH_TOKEN}@github.com/EAL-IT-Technology/ITT3-Special-subjects.git > /dev/null 2>&1
- git push --quiet --set-upstream origin-pages master
