sudo: true

install:
  - sudo apt-get update
  - sudo apt-get -y install make pandoc
  - sudo apt-get -y install
          texlive texlive-base texlive-binaries
          texlive-fonts-recommended texlive-latex-base texlive-latex-extra
          texlive-latex-recommended texlive-pictures texlive-xetex
  - sudo apt-get -y install fonts-freefont-otf fonts-freefont-ttf


script:
  - make

after_success:

- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"

- git add *.pdf
- git commit --message "Travis build"

- git push
